### ISSUE TITLE
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by mathisont** [DeltaBalances/DeltaBalances.github.io#73]
With the

> --disable-reading-from-canvas

option enabled in Chrome, I get:

`Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at setAddrImage (https://deltabalances.github.io/user.js:291:117)
    at setAddressUI (https://deltabalances.github.io/user.js:77:5)
    at getAddress (https://deltabalances.github.io/user.js:59:5)
    at getStorage (https://deltabalances.github.io/balances.js:1697:28)
    at readyInit (https://deltabalances.github.io/balances.js:161:9)
    at HTMLDocument.<anonymous> (https://deltabalances.github.io/balances.js:135:9)
    at j (https://deltabalances.github.io/js/jquery-3.2.1.min.js:2:29999)
    at k (https://deltabalances.github.io/js/jquery-3.2.1.min.js:2:30313)`

**Comment by DeltaBalances** [comment]
Thanks for the fix.
I've noticed Brave browser blocking these, but that didn't throw an exception like this.

I think MyCrypto and MEW get around this, so i'll have to check their approach to these icons.

**Comment by mathisont** [comment]
Non-canvas implementation works great, thnx 👍
